/*
 * defines.h
 *
 *  Created on: 31. 5. 2016
 *      Author: jindra
 */

#ifndef LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_
#define LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_

#define DO_NOT_LOG_SD
#define LOG_LEVEL 4

#define DHT_HUMIDITY_CORRECTION 13.7
//#define DHT_HUMIDITY_CORRECTION_FACTOR 1.35

#define DHT_TEMPERATURE_CORRECTION 0.4

#endif /* LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_ */
