/*
 * defines.h
 *
 *  Created on: 31. 5. 2016
 *      Author: jindra
 */

#ifndef LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_
#define LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_

#define DO_NOT_LOG_SD
#define LOG_LEVEL 4

#ifndef DHT_HUMIDITY_CORRECTION
#define DHT_HUMIDITY_CORRECTION 13.3
#endif

#ifndef DHT_TEMPERATURE_CORRECTION
#define DHT_TEMPERATURE_CORRECTION 0.4
#endif

#endif /* LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_ */
