/*
 * defines.h
 *
 *  Created on: 31. 5. 2016
 *      Author: jindra
 */

#ifndef LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_
#define LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_

#define DO_NOT_LOG_SD
#define LOG_LEVEL 4

#endif /* LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_ */
