/*
 * defines.h
 *
 *  Created on: 31. 5. 2016
 *      Author: jindra
 */

#ifndef LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_
#define LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_


#define USE_SENSOR_FLAGS
#define USE_RTC
#define USE_CONCURENCY


#endif /* LIBRARIES_WEATHERSTATIONDEFINES_DEFINES_H_ */
